-- ---------------Create TRIGGER-----------------
-- create or replace trigger employe_control_job
-- ---controler les ajouts et les modifs de salaires ::
-- before insert or update on  employees

-- for each row 
-- -- ------------------DECLARE----------
-- declare 
-- var_max employees
-- ----------------------------+---------+
-- when (new.job_id != 'AD_PRES' )  ----++
-- --------------------------------------+
-- begin
-- --------------------------MAIN---------------------
-- -- id_j := :new.job_id;
-- ----it 's forbidden to select in a trigger line :p ---MUTATION TABLE
-- select min_salary, max_salary into var_min,var_max from
-- jobs where job_id = :new.job_id ;

--     if :new.salary < var_min or :new.salary > var_max  then
--         raise_application_error(-20800, 'Salary overflow');
--     end if;
-- ---------------------------------------------------
-- end;
-- /